# Generated by Django 6.0.4 on 2026-07-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('guru', 'Guru'), ('murid', 'Murid')], default='murid', max_length=20),
        ),
    ]
