# Generated by Django 6.0.4 on 2026-07-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materi',
            name='mapel',
            field=models.CharField(choices=[('MTK', 'Matematika'), ('IPA', 'IPA'), ('IPS', 'IPS'), ('BIO', 'Biologi'), ('FIS', 'Fisika'), ('KIM', 'Kimia'), ('ING', 'Bahasa Inggris'), ('IND', 'Bahasa Indonesia')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
