# Generated by Django 6.0.4 on 2026-07-14 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materi', '0002_materi_mapel'),
    ]

    operations = [
        migrations.AddField(
            model_name='materi',
            name='kelas',
            field=models.IntegerField(choices=[(1, 'Kelas 1'), (2, 'Kelas 2'), (3, 'Kelas 3'), (4, 'Kelas 4'), (5, 'Kelas 5'), (6, 'Kelas 6')], default=1),
        ),
    ]
